import './styles.css';
import * as THREE from 'three';

type Player = { name: string; club: string; points: number; position: number; multiplier: number; captain?: boolean; vice?: boolean };
type Gameweek = { id: number; points: number; total: number; rank: number; bench: number; captain: string; players: Player[]; events: string[] };

const player = (name: string, club: string, points: number, position: number, multiplier = 1, flags: Partial<Player> = {}): Player => ({ name, club, points, position, multiplier, ...flags });
const gameweeks: Gameweek[] = [
  { id: 1, points: 43, total: 43, rank: 6382778, bench: 1, captain: 'Haaland', events: ['João Pedro returned 11 points', 'Haaland captain blanked on 2', 'Auto-sub: van Ewijk in for Diop'], players: [player('Raya','ARS',6,1),player('Gabriel','ARS',5,2),player('Mitchell','CRY',1,2),player('Shaw','MUN',1,2),player('B.Fernandes','MUN',2,3,1,{vice:true}),player('Szoboszlai','LIV',8,3),player('Mbeumo','MUN',2,3),player('Haaland','MCI',2,4,2,{captain:true}),player('Calvert-Lewin','LEE',1,4),player('João Pedro','CHE',11,4),player('Diop','IPS',2,2,0),player('Yates','NFO',0,3,0),player('Hughes','CRY',0,3,0),player('Palmer','IPS',0,1,0),player('van Ewijk','COV',1,2,0)] },
  { id: 2, points: 111, total: 154, rank: 1630859, bench: 2, captain: 'B.Fernandes', events: ['B.Fernandes captain returned 46 points', 'Mbeumo added 11 points', '1 transfer made · no hit taken'], players: [player('Raya','ARS',6,1),player('Gabriel','ARS',8,2),player('Shaw','MUN',2,2),player('van Ewijk','COV',2,2),player('B.Fernandes','MUN',23,3,2,{captain:true}),player('Slater','HUL',2,3),player('Mbeumo','MUN',11,3),player('Szoboszlai','LIV',4,3),player('João Pedro','CHE',9,4),player('Haaland','MCI',13,4,1,{vice:true}),player('Calvert-Lewin','LEE',8,4),player('Palmer','IPS',0,1,0),player('Mitchell','CRY',0,2,0),player('Diop','IPS',2,2,0),player('Hughes','CRY',0,3,0)] },
  { id: 3, points: 40, total: 194, rank: 1499855, bench: 7, captain: 'Haaland', events: ['Mitchell led the XI with 15 points', 'Haaland captain returned 18 points', '7 points left on the bench'], players: [player('Raya','ARS',0,1),player('Gabriel','ARS',0,2),player('Shaw','MUN',0,2),player('Mitchell','CRY',15,2),player('B.Fernandes','MUN',0,3,1,{vice:true}),player('Slater','HUL',3,3),player('Mbeumo','MUN',0,3),player('Szoboszlai','LIV',3,3),player('João Pedro','CHE',0,4),player('Haaland','MCI',9,4,2,{captain:true}),player('Calvert-Lewin','LEE',1,4),player('Palmer','IPS',0,1,0),player('van Ewijk','COV',3,2,0),player('Diop','IPS',3,2,0),player('Hughes','CRY',1,3,0)] },
];

let selected = 0;
const app = document.querySelector<HTMLDivElement>('#app')!;
const fmt = (n: number) => n.toLocaleString('en-GB');
const initials = (name: string) => name.split(' ').map((p) => p[0]).join('').slice(0, 2);
const positionName = (position: number) => ['','GKP','DEF','MID','FWD'][position];

function render(): void {
  const gw = gameweeks[selected];
  const starters = gw.players.filter((p) => p.multiplier > 0);
  const bench = gw.players.filter((p) => p.multiplier === 0);
  app.innerHTML = `<main class="viewport"><header class="topbar"><div class="brand"><span class="brand-mark">✦</span><div><span>FPL PI MANAGER</span><h1>GAFFER / CONTROL ROOM</h1></div></div><div class="status"><i></i> LIVE SNAPSHOT <b>2026 / 27</b></div></header><section class="dashboard"><div class="scene-panel"><div class="scene-copy"><span class="kicker">THE SEASON ROOM / 03</span><h2>Gameweek <strong>${gw.id}</strong></h2><p>${gw.points} points logged. Every decision, on the board.</p></div><div id="scene" class="three-scene" aria-label="Interactive 3D gaffer room"></div><div class="scene-legend"><span><i class="dot dot--gold"></i> GAFFER</span><span><i class="dot dot--green"></i> ANALYSTS</span><span><i class="dot dot--blue"></i> ACTIVE BOARD</span></div></div><aside class="side-panel"><div class="side-top"><span class="kicker">GAMEWEEK PERFORMANCE</span><span class="sync">SYNCED 04 SEP</span></div><div class="headline"><div><span>GW ${gw.id} SCORE</span><strong>${gw.points}</strong></div><div><span>OVERALL RANK</span><b>${fmt(gw.rank)}</b><small>${gw.id === 1 ? 'Opening rank' : '↑ rank improved'}</small></div></div><div class="history" role="tablist" aria-label="Select gameweek">${gameweeks.map((item, index) => `<button class="history-item ${index === selected ? 'is-active' : ''}" data-gw="${index}" role="tab" aria-selected="${index === selected}"><span>GW ${item.id}</span><strong>${item.points}</strong><small>${item.total} total</small><i style="height:${Math.max(16, item.points / 1.2)}%"></i></button>`).join('')}</div><div class="events"><div class="section-title"><span>KEY EVENTS</span><b>GW ${gw.id}</b></div>${gw.events.map((event, index) => `<div class="event"><span>0${index + 1}</span><p>${event}</p><i class="event-line"></i></div>`).join('')}</div><div class="state-row"><span>CAPTAIN <b>${gw.captain}</b></span><span>BENCH <b>${gw.bench} pts</b></span><span>FREE TRANSFERS <b>1</b></span></div></aside></section><section class="bottom"><div class="roster panel"><div class="panel-title"><span>FIELD / GW ${gw.id}</span><b>${starters.length} STARTERS</b></div><div class="players">${starters.map(playerCard).join('')}</div></div><div class="bench panel"><div class="panel-title"><span>BENCH WATCH</span><b>POINTS LEFT: ${gw.bench}</b></div><div class="bench-players">${bench.map(playerCard).join('')}</div></div></section><footer><span>READ-ONLY / TELEGRAM IS THE APPROVAL SURFACE</span><span>ENTRY 2928517 · FPL API HISTORY</span><div><button class="arrow" data-dir="-1" aria-label="Previous gameweek" ${selected === 0 ? 'disabled' : ''}>←</button><span>${selected + 1} / ${gameweeks.length}</span><button class="arrow" data-dir="1" aria-label="Next gameweek" ${selected === gameweeks.length - 1 ? 'disabled' : ''}>→</button></div></footer></main>`;
  app.querySelectorAll<HTMLButtonElement>('[data-gw]').forEach((button) => button.addEventListener('click', () => { selected = Number(button.dataset.gw); render(); }));
  app.querySelectorAll<HTMLButtonElement>('[data-dir]').forEach((button) => button.addEventListener('click', () => { selected = Math.max(0, Math.min(gameweeks.length - 1, selected + Number(button.dataset.dir))); render(); }));
  mountScene(document.querySelector<HTMLDivElement>('#scene')!);
}
function playerCard(p: Player): string { return `<div class="player"><span class="avatar avatar--${positionName(p.position).toLowerCase()}">${initials(p.name)}</span><span><b>${p.name}</b><small>${p.club} · ${positionName(p.position)}${p.captain ? ' · C' : p.vice ? ' · VC' : ''}</small></span><strong class="player-points">${p.points * p.multiplier}</strong></div>`; }
function mountScene(container: HTMLDivElement): void {
  const scene = new THREE.Scene(); scene.background = new THREE.Color('#111a1c');
  const camera = new THREE.PerspectiveCamera(38, container.clientWidth / container.clientHeight, .1, 100); camera.position.set(6, 5, 9); camera.lookAt(0, 1, 0);
  const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(container.clientWidth, container.clientHeight); renderer.shadowMap.enabled = true; container.appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight('#d5e9d2', '#10201c', 2)); const key = new THREE.DirectionalLight('#f2bf6d', 5); key.position.set(3, 7, 5); key.castShadow = true; scene.add(key);
  const floor = new THREE.Mesh(new THREE.PlaneGeometry(14, 12), new THREE.MeshStandardMaterial({ color: '#192a25', roughness: .8 })); floor.rotation.x = -Math.PI / 2; floor.receiveShadow = true; scene.add(floor);
  const wall = new THREE.Mesh(new THREE.BoxGeometry(14, 7, .25), new THREE.MeshStandardMaterial({ color: '#1d322d' })); wall.position.set(0, 3.5, -3); scene.add(wall);
  const makeBox = (x: number, y: number, z: number, sx: number, sy: number, sz: number, color: string, emissive = '#000000') => { const mesh = new THREE.Mesh(new THREE.BoxGeometry(sx, sy, sz), new THREE.MeshStandardMaterial({ color, emissive, emissiveIntensity: 2 })); mesh.position.set(x, y, z); mesh.castShadow = true; scene.add(mesh); return mesh; };
  makeBox(0, 1.55, -.9, 3.7, 2.2, .16, '#527e60'); makeBox(0, .38, -.9, 4.4, .18, .55, '#a17445');
  for (const x of [-3.3, 3.3]) { makeBox(x, .8, -.8, 1.6, .18, 1.3, '#3b5747'); makeBox(x, 1.55, -1.2, .38, .8, .38, '#bd9c58', '#bd9c58'); }
  const makeAgent = (x: number, z: number, color: string) => { const body = new THREE.Mesh(new THREE.CapsuleGeometry(.25, .62, 4, 8), new THREE.MeshStandardMaterial({ color })); body.position.set(x, .72, z); body.castShadow = true; scene.add(body); const head = new THREE.Mesh(new THREE.SphereGeometry(.22, 12, 12), new THREE.MeshStandardMaterial({ color: '#bd8c68' })); head.position.set(x, 1.3, z); scene.add(head); };
  makeAgent(2.7, -1.4, '#638b72'); makeAgent(-3.3, -1.1, '#52739a'); makeAgent(0, 1.2, '#d19f53');
  const animate = () => { renderer.render(scene, camera); requestAnimationFrame(animate); }; animate();
  new ResizeObserver(() => { camera.aspect = container.clientWidth / container.clientHeight; camera.updateProjectionMatrix(); renderer.setSize(container.clientWidth, container.clientHeight); }).observe(container);
}
render();
